── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.9
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Attaching package: ‘lubridate’

The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union


Attaching package: ‘janitor’

The following objects are masked from ‘package:stats’:

    chisq.test, fisher.test

Error in `mutate()`:
! Problem while computing `event_site_name = ifelse(...)`.
ℹ The error occurred in group 1: tag_code = "3DD.003BF5A900".
Caused by error in `antenna_id %in% ICH_100_bypass`:
! object 'ICH_100_bypass' not found
Backtrace:
     ▆
  1. ├─... %>% ...
  2. ├─dplyr::mutate(...)
  3. ├─dplyr:::mutate.data.frame(...)
  4. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
  5. │   ├─base::withCallingHandlers(...)
  6. │   └─mask$eval_all_mutate(quo)
  7. ├─base::ifelse(...)
  8. ├─antenna_id %in% ICH_100_bypass
  9. └─base::.handleSimpleError(...)
 10.   └─dplyr h(simpleError(msg, call))
 11.     └─rlang::abort(...)
Execution halted
